language: node_js
node_js:
- "9"

deploy:
  provider: script
  script: "cp .npmrc.template $HOME/.npmrc && npm publish"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - berkan.dirim@adidas.com
    on_success: change
    on_failure: always
